Fixed workflow file

diff --git a/.github/workflows/regression_tests.yaml b/.github/workflows/regression_tests.yaml
--- a/.github/workflows/regression_tests.yaml
+++ b/.github/workflows/regression_tests.yaml
@@ -120,53 +120,61 @@ jobs:
           docker start playwright-tests
           sleep 5
 
-      - name: Find and upload Allure report directory
+      - name: Copy allure-results from Docker container
         run: |
           container_id=$(docker ps -qf "name=playwright-tests")
-          echo "Container ID: $container_id"
-          allure_directory=$(docker exec $container_id find / -path /proc -prune -o -type d -name "allure-report" -print -quit)
-          echo "Allure Directory: $allure_directory"
-          if [[ -n "$allure_directory" ]]; then
-            echo "ALLURE_DIRECTORY=$allure_directory" >> $GITHUB_ENV
+          allure_directory=$(docker exec $container_id find / -path /proc -prune -o -type d -name "allure-results" -print -quit)
+          docker cp "$container_id:$allure_directory" ./allure-results
 
-            # Create a temporary directory to store the contents
-            temp_dir="$(mktemp -d)"
-            echo "Temporary Directory: $temp_dir"
+      # - name: Find and upload Allure report directory
+      #   run: |
+      #     container_id=$(docker ps -qf "name=playwright-tests")
+      #     echo "Container ID: $container_id"
+      #     allure_directory=$(docker exec $container_id find / -path /proc -prune -o -type d -name "allure-report" -print -quit)
+      #     echo "Allure Directory: $allure_directory"
+      #     if [[ -n "$allure_directory" ]]; then
+      #       echo "ALLURE_DIRECTORY=$allure_directory" >> $GITHUB_ENV
 
-            # Copy the contents of allure_directory to the temporary directory
-            docker cp "$container_id":"$allure_directory"/. "$temp_dir"
+      #       # Create a temporary directory to store the contents
+      #       temp_dir="$(mktemp -d)"
+      #       echo "Temporary Directory: $temp_dir"
 
-            # Archive the contents of the temporary directory
-            (cd "$(dirname "$temp_dir")" && tar -czf allure-report.tar.gz -C "$(basename "$temp_dir")" .)
+      #       # Copy the contents of allure_directory to the temporary directory
+      #       docker cp "$container_id":"$allure_directory"/. "$temp_dir"
 
-            # Set the path of Allure report archive as output
-            echo "::set-output name=allure_report_archive::$(realpath "$(dirname "$temp_dir")/allure-report.tar.gz")"
+      #       # Archive the contents of the temporary directory
+      #       (cd "$(dirname "$temp_dir")" && tar -czf allure-report.tar.gz -C "$(basename "$temp_dir")" .)
 
-            # Set the environment variable for the archive path
-            export ALLURE_REPORT_ARCHIVE=$(realpath "$(dirname "$temp_dir")/allure-report.tar.gz")
-            echo "ALLURE_REPORT_ARCHIVE=$ALLURE_REPORT_ARCHIVE" >> $GITHUB_ENV
+      #       # Set the path of Allure report archive as output
+      #       echo "::set-output name=allure_report_archive::$(realpath "$(dirname "$temp_dir")/allure-report.tar.gz")"
 
-            # Check if tar was generated successfully
-            if [ $? -eq 0 ]; then
-              echo "Tar archive generated successfully."
+      #       # Set the environment variable for the archive path
+      #       export ALLURE_REPORT_ARCHIVE=$(realpath "$(dirname "$temp_dir")/allure-report.tar.gz")
+      #       echo "ALLURE_REPORT_ARCHIVE=$ALLURE_REPORT_ARCHIVE" >> $GITHUB_ENV
 
-              # Echo the path of the tar file
-              echo "Path of the tar file: $ALLURE_REPORT_ARCHIVE"
+      #       # Check if tar was generated successfully
+      #       if [ $? -eq 0 ]; then
+      #         echo "Tar archive generated successfully."
 
-              # List the contents of the tar file
-              tar -tf "$ALLURE_REPORT_ARCHIVE"
-            else
-              echo "Failed to generate tar archive."
-            fi
-          else
-            echo "Allure directory not found or is empty."
-          fi
+      #         # Echo the path of the tar file
+      #         echo "Path of the tar file: $ALLURE_REPORT_ARCHIVE"
 
-      - name: Upload Allure report archive
+      #         # List the contents of the tar file
+      #         tar -tf "$ALLURE_REPORT_ARCHIVE"
+      #       else
+      #         echo "Failed to generate tar archive."
+      #       fi
+      #     else
+      #       echo "Allure directory not found or is empty."
+      #     fi
+
+
+      - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: allure-report
-          path: ${{ env.ALLURE_REPORT_ARCHIVE }}
+          name: allure-results
+          path: allure-results
+          if-no-files-found: error
 
       - name: Generate a token
         id: generate-token
@@ -177,76 +185,72 @@ jobs:
           owner: "NHSDigital"
           repositories: "ravs-tests,ravs-test-reports"
 
-      - name: Retrieve and extract Allure report artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: allure-report
-          path: allure-report
+      # - name: Retrieve and extract Allure report artifact
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: allure-report
+      #     path: allure-report
 
-      - name: List contents of the downloaded artifact
-        run: |
-          ls -l allure-report
+      # - name: List contents of the downloaded artifact
+      #   run: |
+      #     ls -l allure-report
 
-      - name: Unzip the tar file
-        run: |
-          tar -xzvf allure-report/allure-report.tar.gz -C allure-report
+      # - name: Unzip the tar file
+      #   run: |
+      #     tar -xzvf allure-report/allure-report.tar.gz -C allure-report
 
-      - name: List contents after unzipping
-        run: |
-          ls -l allure-report
+      # - name: List contents after unzipping
+      #   run: |
+      #     ls -l allure-report
 
       # Move the Allure report files to the root of the gh-pages directory
-      - name: Move Allure report files
-        run: |
-          mv allure-report/* .
+      # - name: Move Allure report files
+      #   run: |
+      #     mv allure-report/* .
 
-      - name: Upload Attachments
-        uses: actions/upload-artifact@v4
-        with:
-          name: screenshots
-          path: data/attachments/**
-          if-no-files-found: warn
-          include-hidden-files: false
+      # - name: Upload Attachments
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: screenshots
+      #     path: data/attachments/**
+      #     if-no-files-found: warn
+      #     include-hidden-files: false
 
-      - name: Get branch name
-        id: get_branch_name
-        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
+      # - name: Get branch name
+      #   id: get_branch_name
+      #   run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
 
-      - name: Set destination branch for GitHub Pages
-        id: set-destination-branch
-        run: echo "DESTINATION_BRANCH=gh-pages-${{ inputs.environment }}" >> $GITHUB_ENV
+      # - name: Set destination branch for GitHub Pages
+      #   id: set-destination-branch
+      #   run: echo "DESTINATION_BRANCH=gh-pages-${{ inputs.environment }}" >> $GITHUB_ENV
 
-      - name: Deploy Allure report to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: .
-          destination_branch: "${{ inputs.environment }}"
+      # - name: Deploy Allure report to GitHub Pages
+      #   uses: peaceiris/actions-gh-pages@v4
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     publish_dir: .
+      #     destination_branch: "${{ inputs.environment }}"
 
-      - name: Check contents of gh-pages
-        run: ls -la
+      # - name: Check contents of gh-pages
+      #   run: ls -la
 
-      - name: Get GitHub Pages URL
-        id: pages-url
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const repo = context.repo.repo;
-            const owner = context.repo.owner;
-            const branchName = context.ref.split('/').pop();  // Use the branch name you want to reference
-            const pagesUrl = `https://${owner}.github.io/${repo}/gh-pages-${branchName}`; // Use backticks for template literals
-            core.setOutput('pages_url', pagesUrl);
+      # - name: Get GitHub Pages URL
+      #   id: pages-url
+      #   uses: actions/github-script@v7
+      #   with:
+      #     script: |
+      #       const repo = context.repo.repo;
+      #       const owner = context.repo.owner;
+      #       const branchName = context.ref.split('/').pop();  // Use the branch name you want to reference
+      #       const pagesUrl = `https://${owner}.github.io/${repo}/gh-pages-${branchName}`; // Use backticks for template literals
+      #       core.setOutput('pages_url', pagesUrl);
 
-      - name: Output GitHub Pages URL
-        run: |
-          echo "GitHub Pages URL: ${{ steps.pages-url.outputs.pages_url }}"
+      # - name: Output GitHub Pages URL
+      #   run: |
+      #     echo "GitHub Pages URL: ${{ steps.pages-url.outputs.pages_url }}"
 
       - name: Clean up
         run: docker stop $(docker ps -q) || true
-
-      # - name: Trigger test report generation
-      #   run: |
-      #     python .\scripts\send_tests_results.py --token=${{ steps.generate-token.outputs.token }} --run_id=${{GITHUB.RUN_ID}}
 
       - name: Trigger test report generation
         run: |
@@ -257,8 +261,8 @@ jobs:
           -d '{"ref": "main", "inputs": {"run_id": "'${{ GITHUB.RUN_ID }}'"}}' \
           "https://api.github.com/repos/NHSDigital/ravs-test-reports/actions/workflows/publish_report.yml/dispatches"
 
-      - name: Notify Slack on success
-        if: success()
-        run: |
-          BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||')
-          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Ravs tests finished running for the ${{ inputs.environment }} environment on branch $BRANCH_NAME! Check the Allure report: https://nhsdigital.github.io/ravs-tests/#\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
+      # - name: Notify Slack on success
+      #   if: success()
+      #   run: |
+      #     BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||')
+      #     curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Ravs tests finished running for the ${{ inputs.environment }} environment on branch $BRANCH_NAME! Check the Allure report: https://nhsdigital.github.io/ravs-tests/#\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
